language: r
r:
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: true

r_packages:
  - provParseR
  - rdtLite

notifications:
  slack: endtoendprovenance:DNYqXZWhV1c3eRhkjGYyjCEv

